server:
  port: ":8080"
  read_timeout_seconds: 10
  write_timeout_seconds: 10
  idle_timeout_seconds: 120
database_url: "postgresql://simple_todo_tasks:simple_todo_tasks_password@db/todo_tasks?sslmode=disable"
